#include "pitches.h"

// ── Pin ──────────────────────────────────────────────
const int BUZZER_PIN = 8;

// ── Song registry ────────────────────────────────────
struct Song {
  const int*  notes;
  const int*  durations;
  int   length;
  const char* name;
};

#include "songs.h" //autogenerated

const int NUM_SONGS = sizeof(songs)/sizeof(songs[0]);

// ── Playback state ───────────────────────────────────
int  currentSong  = 0;
int  currentNote  = 0;
bool playing      = false;

unsigned long noteStart    = 0;
unsigned long noteDuration = 0;
bool          inPause      = false;   // true = we're in the silent gap between notes

// ── Helpers ──────────────────────────────────────────
void printStatus() {
  Serial.print("[");
  Serial.print(playing ? "PLAYING" : "PAUSED ");
  Serial.print("] Song ");
  Serial.print(currentSong + 1);
  Serial.print("/");
  Serial.print(NUM_SONGS);
  Serial.print(" - ");
  Serial.print(songs[currentSong].name);
  Serial.print("  (note ");
  Serial.print(currentNote + 1);
  Serial.print("/");
  Serial.print(songs[currentSong].length);
  Serial.println(")");
}

void startNote() {
  Song& s = songs[currentSong];
  int bpm_divisor = 1500;             // tune this to change overall tempo
  int dur = bpm_divisor / pgm_read_word_near(s.durations + currentNote);

  if (s.notes[currentNote] == 0) {   // rest
    noTone(BUZZER_PIN);
  } else {
    tone(BUZZER_PIN, pgm_read_word_near(s.notes + currentNote));
  }

  noteStart    = millis();
  noteDuration = dur;
  inPause      = false;
}

void stopPlayback() {
  noTone(BUZZER_PIN);
  playing = false;
}

void startPlayback() {
  playing = true;
  startNote();
}

void skipSong() {
  noTone(BUZZER_PIN);
  currentSong = (currentSong + 1) % NUM_SONGS;
  currentNote = 0;
  inPause     = false;
  Serial.print("Skipped to: ");
  Serial.println(songs[currentSong].name);
  if (playing) startNote();
}

void printHelp() {
  Serial.println("─────────────────────────────");
  Serial.println(" BUZZER JUKEBOX - Commands");
  Serial.println("─────────────────────────────");
  Serial.println("  p  → Play / Pause");
  Serial.println("  n  → Next song");
  Serial.println("  s  → Status");
  Serial.println("  h  → Help");
  Serial.println("─────────────────────────────");
}

// ── Setup ────────────────────────────────────────────
void setup() {
  Serial.begin(9600);
  pinMode(BUZZER_PIN, OUTPUT);
  printHelp();
  printStatus();
}

// ── Loop ─────────────────────────────────────────────
void loop() {

  // ── Serial input ──
  if (Serial.available()) {
    char cmd = tolower(Serial.read());

    if (cmd == 'p') {
      if (playing) {
        stopPlayback();
        Serial.println("⏸  Paused.");
      } else {
        startPlayback();
        Serial.println("▶  Playing.");
      }
      printStatus();
    }
    else if (cmd == 'n') {
      skipSong();
      printStatus();
    }
    else if (cmd == 's') {
      printStatus();
    }
    else if (cmd == 'h') {
      printHelp();
    }
  }

  // ── Note sequencer ──
  if (!playing) return;

  unsigned long now     = millis();
  unsigned long elapsed = now - noteStart;

  if (!inPause && elapsed >= noteDuration * 9 / 10) {
    // Short silent gap between notes (10 % of note duration)
    noTone(BUZZER_PIN);
    inPause = true;
  }

  if (elapsed >= noteDuration) {
    // Advance to next note
    currentNote++;
    Song& s = songs[currentSong];

    if (currentNote >= s.length) {
      // Song finished – loop it
      currentNote = 0;
      Serial.print("Looping: ");
      Serial.println(s.name);
    }
    startNote();
  }
}